---
- name: Install letsencrypt
  apt:
      name: letsencrypt
      update_cache: yes
  when: ansible_os_family|lower == "debian"

- name: Install letsencrypt
  pacman:
      name: certbot
      state: present
      update_cache: yes
  when: ansible_os_family|lower == "archlinux"
