---
# tasks file for ansible-role-letsencrypt
- name: Install letsencrypt
  apt:
      name: letsencrypt
      update_cache: yes

- name: Copy default nginx configuration
  template:
      src: letsencrypt.conf.j2
      dest: "{{ nginx_vhost_path }}/default"

- name: Reload nginx
  service:
      name: nginx
      state: reloaded

- name: Resolve challenge to obtain certificates
  shell: letsencrypt certonly --webroot -m {{ letsencrypt_email }} -w {{ letsencrypt_webroot }} -d {{ item }}
  args:
      creates: "{{ letsencrypt_domains_directory }}/{{ item }}"
  with_items: "{{ letsencrypt_domains }}"

- name: Add cron job to renew certificates
  cron:
      name: "renew {{ item }}"
      minute: 0
      hour: 0
      job: letsencrypt certonly --webroot -w {{ letsencrypt_webroot }} -d {{ item }} --keep
  with_items: "{{ letsencrypt_domains }}"
