---
# tasks file for ansible-role-letsencrypt
- import_tasks: install.yml

- name: Create user www-data
  user:
      name: www-data
      shell: /bin/bash

- name: Copy default nginx configuration
  template:
      src: letsencrypt.conf.j2
      dest: "{{ nginx_vhost_path }}/default"
      group: www-data
      owner: www-data
  register: nginx_config

- name: Reload nginx
  service:
      name: nginx
      state: reloaded
  when: nginx_config.changed

- name: Resolve challenge to obtain certificates
  shell: "{{ softname }} certonly --webroot -m {{ letsencrypt_email }} -w {{ letsencrypt_webroot }} -d {{ item }} -n --agree-tos"
  args:
      creates: "{{ letsencrypt_domains_directory }}/{{ item }}"
  with_items: "{{ letsencrypt_domains }}"
  when: letsencrypt_tos_agreed

- name: Add cron job to renew certificates
  cron:
      name: "renew {{ item }}"
      minute: 0
      hour: 0
      job: "{{ softname }} certonly --webroot -m {{ letsencrypt_email }} -w {{ letsencrypt_webroot }} -d {{ item }} -n --keep"
  with_items: "{{ letsencrypt_domains }}"
